# Generated by Django 6.0.4 on 2026-05-15 04:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialOperacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('crear_producto', 'Creó producto'), ('editar_producto', 'Editó producto'), ('eliminar_producto', 'Eliminó producto'), ('crear_categoria', 'Creó categoría'), ('editar_categoria', 'Editó categoría'), ('eliminar_categoria', 'Eliminó categoría'), ('registrar_movimiento', 'Registró movimiento'), ('registro_usuario', 'Registró usuario'), ('activar_2fa', 'Activó 2FA'), ('desactivar_2fa', 'Desactivó 2FA')], max_length=30)),
                ('detalle', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Operación',
                'verbose_name_plural': 'Historial de Operaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
